/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'action' : string,
  'actorId' : string,
  'logId' : string,
  'timestamp' : bigint,
}
export interface AdminStats {
  'totalStudents' : bigint,
  'activeRegistrations' : bigint,
  'registeredStudents' : bigint,
  'totalCourses' : bigint,
}
export interface BulkStudentRow {
  'enrollmentId' : string,
  'name' : string,
  'department' : string,
}
export interface CourseInput {
  'credits' : bigint,
  'maxSeats' : bigint,
  'facultyName' : string,
  'schedule' : string,
  'courseCode' : string,
  'courseName' : string,
}
export interface CourseUpdateInput {
  'credits' : [] | [bigint],
  'maxSeats' : [] | [bigint],
  'facultyName' : [] | [string],
  'schedule' : [] | [string],
  'courseName' : [] | [string],
}
export interface CourseView {
  'credits' : bigint,
  'maxSeats' : bigint,
  'createdAt' : bigint,
  'facultyName' : string,
  'schedule' : string,
  'courseCode' : string,
  'courseName' : string,
  'enrolledCount' : bigint,
}
export type OkOrErr = { 'ok' : null } |
  { 'err' : string };
export type OkTextOrErr = { 'ok' : string } |
  { 'err' : string };
export interface PasswordResetRequestView {
  'status' : PasswordResetStatus,
  'requestId' : string,
  'enrollmentId' : string,
  'requestedAt' : bigint,
  'resolvedAt' : [] | [bigint],
}
export type PasswordResetStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RegistrationView {
  'courseCodes' : Array<string>,
  'enrollmentId' : string,
  'createdAt' : bigint,
  'locked' : boolean,
  'lockTimestamp' : [] | [bigint],
  'updatedAt' : bigint,
  'totalCredits' : bigint,
  'registrationId' : string,
  'pdfFileId' : [] | [string],
}
export interface StudentProfileInput {
  'motherName' : [] | [string],
  'email' : [] | [string],
  'fatherName' : [] | [string],
  'rollNumber' : [] | [string],
  'photoFileId' : [] | [string],
  'mobile' : [] | [string],
  'className' : [] | [string],
}
export interface StudentUpdateInput {
  'name' : [] | [string],
  'passwordHash' : [] | [string],
  'department' : [] | [string],
  'profileComplete' : [] | [boolean],
}
export interface StudentView {
  'enrollmentId' : string,
  'name' : string,
  'createdAt' : bigint,
  'motherName' : [] | [string],
  'email' : [] | [string],
  'updatedAt' : bigint,
  'fatherName' : [] | [string],
  'rollNumber' : [] | [string],
  'photoFileId' : [] | [string],
  'isLocked' : boolean,
  'mobile' : [] | [string],
  'department' : string,
  'className' : [] | [string],
  'profileComplete' : boolean,
}
export interface _SERVICE {
  'addCourse' : ActorMethod<[CourseInput], OkOrErr>,
  'addStudent' : ActorMethod<[string, string, string], OkOrErr>,
  'adminAddCourseToStudent' : ActorMethod<[string, string], OkOrErr>,
  'adminLogin' : ActorMethod<[string], OkTextOrErr>,
  'adminRemoveCourseFromStudent' : ActorMethod<[string, string], OkOrErr>,
  'adminResetPassword' : ActorMethod<[string, string], OkOrErr>,
  'bulkUploadStudents' : ActorMethod<
    [Array<BulkStudentRow>],
    { 'imported' : bigint, 'errors' : Array<string> }
  >,
  'deleteCourse' : ActorMethod<[string], OkOrErr>,
  'deleteStudent' : ActorMethod<[string], OkOrErr>,
  'finalSubmitRegistration' : ActorMethod<[string], OkTextOrErr>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllCourses' : ActorMethod<[], Array<CourseView>>,
  'getAllRegistrations' : ActorMethod<[], Array<RegistrationView>>,
  'getAllStudents' : ActorMethod<[], Array<StudentView>>,
  'getCourse' : ActorMethod<[string], [] | [CourseView]>,
  'getPasswordResetRequests' : ActorMethod<[], Array<PasswordResetRequestView>>,
  'getRecentActivity' : ActorMethod<[], Array<ActivityLog>>,
  'getRegistration' : ActorMethod<[string], [] | [RegistrationView]>,
  'getStudent' : ActorMethod<[string], [] | [StudentView]>,
  'getStudentPassword' : ActorMethod<[string], [] | [string]>,
  'registerCourses' : ActorMethod<[string, Array<string>], OkOrErr>,
  'requestPasswordReset' : ActorMethod<[string], OkOrErr>,
  'studentLogin' : ActorMethod<[string, string], OkTextOrErr>,
  'toggleStudentLock' : ActorMethod<
    [string, boolean],
    { 'ok' : StudentView } |
      { 'err' : string }
  >,
  'unlockRegistration' : ActorMethod<[string], OkOrErr>,
  'updateCourse' : ActorMethod<[string, CourseUpdateInput], OkOrErr>,
  'updatePdfFileId' : ActorMethod<[string, string], OkOrErr>,
  'updateStudent' : ActorMethod<[string, StudentUpdateInput], OkOrErr>,
  'updateStudentProfile' : ActorMethod<[string, StudentProfileInput], OkOrErr>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];