/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CourseInput = IDL.Record({
  'credits' : IDL.Nat,
  'maxSeats' : IDL.Nat,
  'facultyName' : IDL.Text,
  'schedule' : IDL.Text,
  'courseCode' : IDL.Text,
  'courseName' : IDL.Text,
});
export const OkOrErr = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const OkTextOrErr = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const BulkStudentRow = IDL.Record({
  'enrollmentId' : IDL.Text,
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'activeRegistrations' : IDL.Nat,
  'registeredStudents' : IDL.Nat,
  'totalCourses' : IDL.Nat,
});
export const CourseView = IDL.Record({
  'credits' : IDL.Nat,
  'maxSeats' : IDL.Nat,
  'createdAt' : IDL.Int,
  'facultyName' : IDL.Text,
  'schedule' : IDL.Text,
  'courseCode' : IDL.Text,
  'courseName' : IDL.Text,
  'enrolledCount' : IDL.Nat,
});
export const RegistrationView = IDL.Record({
  'courseCodes' : IDL.Vec(IDL.Text),
  'enrollmentId' : IDL.Text,
  'createdAt' : IDL.Int,
  'locked' : IDL.Bool,
  'lockTimestamp' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'totalCredits' : IDL.Nat,
  'registrationId' : IDL.Text,
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const StudentView = IDL.Record({
  'enrollmentId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'motherName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'fatherName' : IDL.Opt(IDL.Text),
  'rollNumber' : IDL.Opt(IDL.Text),
  'photoFileId' : IDL.Opt(IDL.Text),
  'isLocked' : IDL.Bool,
  'mobile' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
  'className' : IDL.Opt(IDL.Text),
  'profileComplete' : IDL.Bool,
});
export const PasswordResetStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PasswordResetRequestView = IDL.Record({
  'status' : PasswordResetStatus,
  'requestId' : IDL.Text,
  'enrollmentId' : IDL.Text,
  'requestedAt' : IDL.Int,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const ActivityLog = IDL.Record({
  'action' : IDL.Text,
  'actorId' : IDL.Text,
  'logId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CourseUpdateInput = IDL.Record({
  'credits' : IDL.Opt(IDL.Nat),
  'maxSeats' : IDL.Opt(IDL.Nat),
  'facultyName' : IDL.Opt(IDL.Text),
  'schedule' : IDL.Opt(IDL.Text),
  'courseName' : IDL.Opt(IDL.Text),
});
export const StudentUpdateInput = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
  'profileComplete' : IDL.Opt(IDL.Bool),
});
export const StudentProfileInput = IDL.Record({
  'motherName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'fatherName' : IDL.Opt(IDL.Text),
  'rollNumber' : IDL.Opt(IDL.Text),
  'photoFileId' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Opt(IDL.Text),
  'className' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCourse' : IDL.Func([CourseInput], [OkOrErr], []),
  'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [OkOrErr], []),
  'adminAddCourseToStudent' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
  'adminLogin' : IDL.Func([IDL.Text], [OkTextOrErr], []),
  'adminRemoveCourseFromStudent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [OkOrErr],
      [],
    ),
  'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
  'bulkUploadStudents' : IDL.Func(
      [IDL.Vec(BulkStudentRow)],
      [IDL.Record({ 'imported' : IDL.Nat, 'errors' : IDL.Vec(IDL.Text) })],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Text], [OkOrErr], []),
  'deleteStudent' : IDL.Func([IDL.Text], [OkOrErr], []),
  'finalSubmitRegistration' : IDL.Func([IDL.Text], [OkTextOrErr], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(CourseView)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(RegistrationView)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(CourseView)], ['query']),
  'getPasswordResetRequests' : IDL.Func(
      [],
      [IDL.Vec(PasswordResetRequestView)],
      ['query'],
    ),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getRegistration' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RegistrationView)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentView)], ['query']),
  'getStudentPassword' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'registerCourses' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [OkOrErr], []),
  'requestPasswordReset' : IDL.Func([IDL.Text], [OkOrErr], []),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [OkTextOrErr], []),
  'toggleStudentLock' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : StudentView, 'err' : IDL.Text })],
      [],
    ),
  'unlockRegistration' : IDL.Func([IDL.Text], [OkOrErr], []),
  'updateCourse' : IDL.Func([IDL.Text, CourseUpdateInput], [OkOrErr], []),
  'updatePdfFileId' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
  'updateStudent' : IDL.Func([IDL.Text, StudentUpdateInput], [OkOrErr], []),
  'updateStudentProfile' : IDL.Func(
      [IDL.Text, StudentProfileInput],
      [OkOrErr],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CourseInput = IDL.Record({
    'credits' : IDL.Nat,
    'maxSeats' : IDL.Nat,
    'facultyName' : IDL.Text,
    'schedule' : IDL.Text,
    'courseCode' : IDL.Text,
    'courseName' : IDL.Text,
  });
  const OkOrErr = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const OkTextOrErr = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const BulkStudentRow = IDL.Record({
    'enrollmentId' : IDL.Text,
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'activeRegistrations' : IDL.Nat,
    'registeredStudents' : IDL.Nat,
    'totalCourses' : IDL.Nat,
  });
  const CourseView = IDL.Record({
    'credits' : IDL.Nat,
    'maxSeats' : IDL.Nat,
    'createdAt' : IDL.Int,
    'facultyName' : IDL.Text,
    'schedule' : IDL.Text,
    'courseCode' : IDL.Text,
    'courseName' : IDL.Text,
    'enrolledCount' : IDL.Nat,
  });
  const RegistrationView = IDL.Record({
    'courseCodes' : IDL.Vec(IDL.Text),
    'enrollmentId' : IDL.Text,
    'createdAt' : IDL.Int,
    'locked' : IDL.Bool,
    'lockTimestamp' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'totalCredits' : IDL.Nat,
    'registrationId' : IDL.Text,
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const StudentView = IDL.Record({
    'enrollmentId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'motherName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'fatherName' : IDL.Opt(IDL.Text),
    'rollNumber' : IDL.Opt(IDL.Text),
    'photoFileId' : IDL.Opt(IDL.Text),
    'isLocked' : IDL.Bool,
    'mobile' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
    'className' : IDL.Opt(IDL.Text),
    'profileComplete' : IDL.Bool,
  });
  const PasswordResetStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PasswordResetRequestView = IDL.Record({
    'status' : PasswordResetStatus,
    'requestId' : IDL.Text,
    'enrollmentId' : IDL.Text,
    'requestedAt' : IDL.Int,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const ActivityLog = IDL.Record({
    'action' : IDL.Text,
    'actorId' : IDL.Text,
    'logId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CourseUpdateInput = IDL.Record({
    'credits' : IDL.Opt(IDL.Nat),
    'maxSeats' : IDL.Opt(IDL.Nat),
    'facultyName' : IDL.Opt(IDL.Text),
    'schedule' : IDL.Opt(IDL.Text),
    'courseName' : IDL.Opt(IDL.Text),
  });
  const StudentUpdateInput = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
    'profileComplete' : IDL.Opt(IDL.Bool),
  });
  const StudentProfileInput = IDL.Record({
    'motherName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'fatherName' : IDL.Opt(IDL.Text),
    'rollNumber' : IDL.Opt(IDL.Text),
    'photoFileId' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Opt(IDL.Text),
    'className' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCourse' : IDL.Func([CourseInput], [OkOrErr], []),
    'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [OkOrErr], []),
    'adminAddCourseToStudent' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
    'adminLogin' : IDL.Func([IDL.Text], [OkTextOrErr], []),
    'adminRemoveCourseFromStudent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [OkOrErr],
        [],
      ),
    'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
    'bulkUploadStudents' : IDL.Func(
        [IDL.Vec(BulkStudentRow)],
        [IDL.Record({ 'imported' : IDL.Nat, 'errors' : IDL.Vec(IDL.Text) })],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Text], [OkOrErr], []),
    'deleteStudent' : IDL.Func([IDL.Text], [OkOrErr], []),
    'finalSubmitRegistration' : IDL.Func([IDL.Text], [OkTextOrErr], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(CourseView)], ['query']),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(RegistrationView)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(CourseView)], ['query']),
    'getPasswordResetRequests' : IDL.Func(
        [],
        [IDL.Vec(PasswordResetRequestView)],
        ['query'],
      ),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getRegistration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RegistrationView)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentView)], ['query']),
    'getStudentPassword' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'registerCourses' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [OkOrErr], []),
    'requestPasswordReset' : IDL.Func([IDL.Text], [OkOrErr], []),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [OkTextOrErr], []),
    'toggleStudentLock' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : StudentView, 'err' : IDL.Text })],
        [],
      ),
    'unlockRegistration' : IDL.Func([IDL.Text], [OkOrErr], []),
    'updateCourse' : IDL.Func([IDL.Text, CourseUpdateInput], [OkOrErr], []),
    'updatePdfFileId' : IDL.Func([IDL.Text, IDL.Text], [OkOrErr], []),
    'updateStudent' : IDL.Func([IDL.Text, StudentUpdateInput], [OkOrErr], []),
    'updateStudentProfile' : IDL.Func(
        [IDL.Text, StudentProfileInput],
        [OkOrErr],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };