/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegistrationView {
    courseCodes: Array<string>;
    enrollmentId: string;
    createdAt: bigint;
    locked: boolean;
    lockTimestamp?: bigint;
    updatedAt: bigint;
    totalCredits: bigint;
    registrationId: string;
    pdfFileId?: string;
}
export interface StudentView {
    enrollmentId: string;
    name: string;
    createdAt: bigint;
    motherName?: string;
    email?: string;
    updatedAt: bigint;
    fatherName?: string;
    rollNumber?: string;
    photoFileId?: string;
    isLocked: boolean;
    mobile?: string;
    department: string;
    className?: string;
    profileComplete: boolean;
}
export interface PasswordResetRequestView {
    status: PasswordResetStatus;
    requestId: string;
    enrollmentId: string;
    requestedAt: bigint;
    resolvedAt?: bigint;
}
export type OkOrErr = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface ActivityLog {
    action: string;
    actorId: string;
    logId: string;
    timestamp: bigint;
}
export interface CourseUpdateInput {
    credits?: bigint;
    maxSeats?: bigint;
    facultyName?: string;
    schedule?: string;
    courseName?: string;
}
export interface StudentUpdateInput {
    name?: string;
    passwordHash?: string;
    department?: string;
    profileComplete?: boolean;
}
export interface BulkStudentRow {
    enrollmentId: string;
    name: string;
    department: string;
}
export interface CourseInput {
    credits: bigint;
    maxSeats: bigint;
    facultyName: string;
    schedule: string;
    courseCode: string;
    courseName: string;
}
export type OkTextOrErr = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface StudentProfileInput {
    motherName?: string;
    email?: string;
    fatherName?: string;
    rollNumber?: string;
    photoFileId?: string;
    mobile?: string;
    className?: string;
}
export interface AdminStats {
    totalStudents: bigint;
    activeRegistrations: bigint;
    registeredStudents: bigint;
    totalCourses: bigint;
}
export interface CourseView {
    credits: bigint;
    maxSeats: bigint;
    createdAt: bigint;
    facultyName: string;
    schedule: string;
    courseCode: string;
    courseName: string;
    enrolledCount: bigint;
}
export enum PasswordResetStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    addCourse(input: CourseInput): Promise<OkOrErr>;
    addStudent(name: string, enrollmentId: string, department: string): Promise<OkOrErr>;
    adminAddCourseToStudent(enrollmentId: string, courseCode: string): Promise<OkOrErr>;
    adminLogin(password: string): Promise<OkTextOrErr>;
    adminRemoveCourseFromStudent(enrollmentId: string, courseCode: string): Promise<OkOrErr>;
    adminResetPassword(enrollmentId: string, newPassword: string): Promise<OkOrErr>;
    bulkUploadStudents(rows: Array<BulkStudentRow>): Promise<{
        imported: bigint;
        errors: Array<string>;
    }>;
    deleteCourse(courseCode: string): Promise<OkOrErr>;
    deleteStudent(enrollmentId: string): Promise<OkOrErr>;
    finalSubmitRegistration(enrollmentId: string): Promise<OkTextOrErr>;
    getAdminStats(): Promise<AdminStats>;
    getAllCourses(): Promise<Array<CourseView>>;
    getAllRegistrations(): Promise<Array<RegistrationView>>;
    getAllStudents(): Promise<Array<StudentView>>;
    getCourse(courseCode: string): Promise<CourseView | null>;
    getPasswordResetRequests(): Promise<Array<PasswordResetRequestView>>;
    getRecentActivity(): Promise<Array<ActivityLog>>;
    getRegistration(enrollmentId: string): Promise<RegistrationView | null>;
    getStudent(enrollmentId: string): Promise<StudentView | null>;
    getStudentPassword(enrollmentId: string): Promise<string | null>;
    registerCourses(enrollmentId: string, courseCodes: Array<string>): Promise<OkOrErr>;
    requestPasswordReset(enrollmentId: string): Promise<OkOrErr>;
    studentLogin(enrollmentId: string, password: string): Promise<OkTextOrErr>;
    toggleStudentLock(enrollmentId: string, lock: boolean): Promise<{
        __kind__: "ok";
        ok: StudentView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlockRegistration(enrollmentId: string): Promise<OkOrErr>;
    updateCourse(courseCode: string, input: CourseUpdateInput): Promise<OkOrErr>;
    updatePdfFileId(enrollmentId: string, pdfFileId: string): Promise<OkOrErr>;
    updateStudent(enrollmentId: string, updates: StudentUpdateInput): Promise<OkOrErr>;
    updateStudentProfile(enrollmentId: string, profileData: StudentProfileInput): Promise<OkOrErr>;
}
import type { CourseUpdateInput as _CourseUpdateInput, CourseView as _CourseView, OkOrErr as _OkOrErr, OkTextOrErr as _OkTextOrErr, PasswordResetRequestView as _PasswordResetRequestView, PasswordResetStatus as _PasswordResetStatus, RegistrationView as _RegistrationView, StudentProfileInput as _StudentProfileInput, StudentUpdateInput as _StudentUpdateInput, StudentView as _StudentView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCourse(arg0: CourseInput): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAddCourseToStudent(arg0: string, arg1: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCourseToStudent(arg0, arg1);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCourseToStudent(arg0, arg1);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<OkTextOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveCourseFromStudent(arg0: string, arg1: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveCourseFromStudent(arg0, arg1);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveCourseFromStudent(arg0, arg1);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminResetPassword(arg0: string, arg1: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetPassword(arg0, arg1);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetPassword(arg0, arg1);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkUploadStudents(arg0: Array<BulkStudentRow>): Promise<{
        imported: bigint;
        errors: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadStudents(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStudent(arg0: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async finalSubmitRegistration(arg0: string): Promise<OkTextOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.finalSubmitRegistration(arg0);
                return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalSubmitRegistration(arg0);
            return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllCourses(): Promise<Array<CourseView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return result;
        }
    }
    async getAllRegistrations(): Promise<Array<RegistrationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrations();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrations();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: string): Promise<CourseView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPasswordResetRequests(): Promise<Array<PasswordResetRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPasswordResetRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPasswordResetRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentActivity(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivity();
            return result;
        }
    }
    async getRegistration(arg0: string): Promise<RegistrationView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistration(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistration(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentPassword(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentPassword(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentPassword(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCourses(arg0: string, arg1: Array<string>): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCourses(arg0, arg1);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCourses(arg0, arg1);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestPasswordReset(arg0: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPasswordReset(arg0);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPasswordReset(arg0);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async studentLogin(arg0: string, arg1: string): Promise<OkTextOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.studentLogin(arg0, arg1);
                return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentLogin(arg0, arg1);
            return from_candid_OkTextOrErr_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleStudentLock(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: StudentView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStudentLock(arg0, arg1);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStudentLock(arg0, arg1);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockRegistration(arg0: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockRegistration(arg0);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockRegistration(arg0);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCourse(arg0: string, arg1: CourseUpdateInput): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, to_candid_CourseUpdateInput_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, to_candid_CourseUpdateInput_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePdfFileId(arg0: string, arg1: string): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePdfFileId(arg0, arg1);
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePdfFileId(arg0, arg1);
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: string, arg1: StudentUpdateInput): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_StudentUpdateInput_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_StudentUpdateInput_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudentProfile(arg0: string, arg1: StudentProfileInput): Promise<OkOrErr> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentProfile(arg0, to_candid_StudentProfileInput_n26(this._uploadFile, this._downloadFile, arg1));
                return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentProfile(arg0, to_candid_StudentProfileInput_n26(this._uploadFile, this._downloadFile, arg1));
            return from_candid_OkOrErr_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_OkOrErr_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OkOrErr): OkOrErr {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_OkTextOrErr_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OkTextOrErr): OkTextOrErr {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PasswordResetRequestView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PasswordResetRequestView): PasswordResetRequestView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PasswordResetStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PasswordResetStatus): PasswordResetStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationView): RegistrationView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StudentView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentView): StudentView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseView]): CourseView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RegistrationView]): RegistrationView | null {
    return value.length === 0 ? null : from_candid_RegistrationView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : from_candid_StudentView_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enrollmentId: string;
    name: string;
    createdAt: bigint;
    motherName: [] | [string];
    email: [] | [string];
    updatedAt: bigint;
    fatherName: [] | [string];
    rollNumber: [] | [string];
    photoFileId: [] | [string];
    isLocked: boolean;
    mobile: [] | [string];
    department: string;
    className: [] | [string];
    profileComplete: boolean;
}): {
    enrollmentId: string;
    name: string;
    createdAt: bigint;
    motherName?: string;
    email?: string;
    updatedAt: bigint;
    fatherName?: string;
    rollNumber?: string;
    photoFileId?: string;
    isLocked: boolean;
    mobile?: string;
    department: string;
    className?: string;
    profileComplete: boolean;
} {
    return {
        enrollmentId: value.enrollmentId,
        name: value.name,
        createdAt: value.createdAt,
        motherName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.motherName)),
        email: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        fatherName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.fatherName)),
        rollNumber: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.rollNumber)),
        photoFileId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.photoFileId)),
        isLocked: value.isLocked,
        mobile: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.mobile)),
        department: value.department,
        className: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.className)),
        profileComplete: value.profileComplete
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PasswordResetStatus;
    requestId: string;
    enrollmentId: string;
    requestedAt: bigint;
    resolvedAt: [] | [bigint];
}): {
    status: PasswordResetStatus;
    requestId: string;
    enrollmentId: string;
    requestedAt: bigint;
    resolvedAt?: bigint;
} {
    return {
        status: from_candid_PasswordResetStatus_n17(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        enrollmentId: value.enrollmentId,
        requestedAt: value.requestedAt,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseCodes: Array<string>;
    enrollmentId: string;
    createdAt: bigint;
    locked: boolean;
    lockTimestamp: [] | [bigint];
    updatedAt: bigint;
    totalCredits: bigint;
    registrationId: string;
    pdfFileId: [] | [string];
}): {
    courseCodes: Array<string>;
    enrollmentId: string;
    createdAt: bigint;
    locked: boolean;
    lockTimestamp?: bigint;
    updatedAt: bigint;
    totalCredits: bigint;
    registrationId: string;
    pdfFileId?: string;
} {
    return {
        courseCodes: value.courseCodes,
        enrollmentId: value.enrollmentId,
        createdAt: value.createdAt,
        locked: value.locked,
        lockTimestamp: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lockTimestamp)),
        updatedAt: value.updatedAt,
        totalCredits: value.totalCredits,
        registrationId: value.registrationId,
        pdfFileId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.pdfFileId))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PasswordResetStatus {
    return "pending" in value ? PasswordResetStatus.pending : "approved" in value ? PasswordResetStatus.approved : "rejected" in value ? PasswordResetStatus.rejected : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StudentView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StudentView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StudentView_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentView>): Array<StudentView> {
    return value.map((x)=>from_candid_StudentView_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PasswordResetRequestView>): Array<PasswordResetRequestView> {
    return value.map((x)=>from_candid_PasswordResetRequestView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegistrationView>): Array<RegistrationView> {
    return value.map((x)=>from_candid_RegistrationView_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CourseUpdateInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseUpdateInput): _CourseUpdateInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfileInput_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfileInput): _StudentProfileInput {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StudentUpdateInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentUpdateInput): _StudentUpdateInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credits?: bigint;
    maxSeats?: bigint;
    facultyName?: string;
    schedule?: string;
    courseName?: string;
}): {
    credits: [] | [bigint];
    maxSeats: [] | [bigint];
    facultyName: [] | [string];
    schedule: [] | [string];
    courseName: [] | [string];
} {
    return {
        credits: value.credits ? candid_some(value.credits) : candid_none(),
        maxSeats: value.maxSeats ? candid_some(value.maxSeats) : candid_none(),
        facultyName: value.facultyName ? candid_some(value.facultyName) : candid_none(),
        schedule: value.schedule ? candid_some(value.schedule) : candid_none(),
        courseName: value.courseName ? candid_some(value.courseName) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    passwordHash?: string;
    department?: string;
    profileComplete?: boolean;
}): {
    name: [] | [string];
    passwordHash: [] | [string];
    department: [] | [string];
    profileComplete: [] | [boolean];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        passwordHash: value.passwordHash ? candid_some(value.passwordHash) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none(),
        profileComplete: value.profileComplete ? candid_some(value.profileComplete) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motherName?: string;
    email?: string;
    fatherName?: string;
    rollNumber?: string;
    photoFileId?: string;
    mobile?: string;
    className?: string;
}): {
    motherName: [] | [string];
    email: [] | [string];
    fatherName: [] | [string];
    rollNumber: [] | [string];
    photoFileId: [] | [string];
    mobile: [] | [string];
    className: [] | [string];
} {
    return {
        motherName: value.motherName ? candid_some(value.motherName) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        fatherName: value.fatherName ? candid_some(value.fatherName) : candid_none(),
        rollNumber: value.rollNumber ? candid_some(value.rollNumber) : candid_none(),
        photoFileId: value.photoFileId ? candid_some(value.photoFileId) : candid_none(),
        mobile: value.mobile ? candid_some(value.mobile) : candid_none(),
        className: value.className ? candid_some(value.className) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
